# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup

%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from config import g_key
gmaps.configure(api_key=g_key)

In [2]:
figure = gmaps.figure()
figure

Figure(layout=FigureLayout(height='420px'))

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [57]:
#vaca_cities_df = pd.read_csv (r'C:\Users\ICPC\Desktop\Data_Sci_Homework\Python-API-HW\WeatherPy\cities_df.csv')
vaca_cities_df = pd.read_csv ('cities_df.csv')

print (vaca_cities_df)

          City  Cloudiness  Country          Date  Humidity      Lat  \
0      colares        20.0   3600.0  1.620053e+09      55.0  38.7992
1       barrow        90.0 -28800.0  1.620053e+09      86.0  71.2906
2       avarua        90.0 -36000.0  1.620053e+09      73.0 -21.2078
3       hasaki        20.0  32400.0  1.620053e+09      38.0  35.7333
4      kunming         0.0  28800.0  1.620053e+09      52.0  25.0389
..         ...         ...      ...           ...       ...      ...
546  mackenzie        90.0 -25200.0  1.620054e+09      87.0  55.2999
547   monrovia        75.0      0.0  1.620054e+09      66.0   6.3005
548      seoul         0.0  32400.0  1.620054e+09      58.0  37.5683
549  dubrajpur        90.0  19800.0  1.620054e+09      94.0  23.8000
550      rocha        64.0 -10800.0  1.620054e+09      52.0 -34.4833

          Lng  Max Temp  Windspeed
0     -9.4469     73.00      10.36
1   -156.7887     15.80       3.27
2   -159.7750     75.20       8.05
3    140.8333     59.00      10.36
4    102.7183     66.20      13.42
..        ...       ...        ...
546 -123.1698     35.60       3.44
547  -10.7969     91.40      10.36
548  126.9778     53.60       3.44
549   87.3833     77.00       5.75
550  -54.3333     77.09      12.71

[551 rows x 9 columns]

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [58]:
humidity = vaca_cities_df["Humidity"]
maxhumidity = humidity.max()
locations = vaca_cities_df[["Lat", "Lng"]]
locations

         Lat       Lng
0    38.7992   -9.4469
1    71.2906 -156.7887
2   -21.2078 -159.7750
3    35.7333  140.8333
4    25.0389  102.7183
..       ...       ...
546  55.2999 -123.1698
547   6.3005  -10.7969
548  37.5683  126.9778
549  23.8000   87.3833
550 -34.4833  -54.3333

[551 rows x 2 columns]

In [70]:
figure = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,dissipating=False, max_intensity=maxhumidity,point_radius=2)
figure.add_layer(heat_layer)
figure = gmaps.figure(center=(46.0, -5.0), zoom_level=8)
figure

Figure(layout=FigureLayout(height='420px'))

In [60]:
figure_layout = {
    'width': '400px',
    'height': '400px',
    'border': '1px solid black',
    'padding': '1px'
}
#figure(layout=)
gmaps.figure(layout=figure_layout)
figure

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [61]:
best_weather_df = vaca_cities_df[(vaca_cities_df['Max Temp'].between(75,92)) & (vaca_cities_df['Windspeed']<10) & (vaca_cities_df['Humidity']<=45)]
best_weather_df.reset_index(inplace=True)
del best_weather_df['index']
best_weather_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Windspeed
0,hermanus,83.0,7200.0,1.620053e+09,38.0,-34.4187,19.2345,80.01,2.01
1,tomatlan,2.0,-18000.0,1.620053e+09,31.0,19.9333,-105.2500,79.61,0.40
2,cabo san lucas,1.0,-21600.0,1.620053e+09,17.0,22.8909,-109.9124,77.00,6.91
3,lata,34.0,3600.0,1.620053e+09,40.0,40.1629,-8.3327,75.00,9.84
4,bardiyah,100.0,7200.0,1.620053e+09,24.0,31.7561,25.0865,88.99,6.93
5,gat,31.0,10800.0,1.620053e+09,29.0,31.6100,34.7642,84.00,9.40
6,ongandjera,9.0,7200.0,1.620053e+09,32.0,-17.8833,15.0667,83.82,9.26
7,edelira,0.0,-14400.0,1.620053e+09,36.0,-26.7500,-55.2667,85.01,8.63
8,chechat,62.0,19800.0,1.620053e+09,22.0,24.7667,75.8833,89.76,6.46
9,disa,70.0,19800.0,1.620053e+09,20.0,24.2500,72.1667,89.71,7.56
10,seoni,60.0,19800.0,1.620053e+09,35.0,22.0833,79.5333,81.99,3.67
11,buritizeiro,0.0,-10800.0,1.620053e+09,39.0,-17.3511,-44.9622,83.26,4.85
12,cassilandia,0.0,-14400.0,1.620053e+09,27.0,-19.1133,-51.7342,87.60,7.31
13,vathi,0.0,10800.0,1.620053e+09,30.0,38.4000,23.6000,86.00,3.44
14,khoni,0.0,14400.0,1.620053e+09,27.0,42.3226,42.4206,87.80,3.44
15,springbok,99.0,7200.0,1.620053e+09,21.0,-29.6643,17.8865,76.05,4.03
16,gazanjyk,100.0,18000.0,1.620053e+09,18.0,39.2446,55.5154,77.38,6.17
17,kruisfontein,2.0,7200.0,1.620053e+09,36.0,-34.0033,24.7314,76.69,2.64
18,najran,75.0,10800.0,1.620053e+09,14.0,17.4924,44.1277,91.40,6.91
19,kondagaon,49.0,19800.0,1.620053e+09,35.0,19.6000,81.6667,82.63,3.83
20,sesheke,10.0,7200.0,1.620053e+09,32.0,-17.4759,24.2968,79.38,6.35
21,vredendal,100.0,7200.0,1.620054e+09,28.0,-31.6683,18.5012,77.72,9.33

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [62]:
hotel_df = []

for x in range(len(best_weather_df)):
    lat = best_weather_df.loc[x]['Lat']
    lng = best_weather_df.loc[x]['Lng']
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }
    
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    requested = requests.get(url, params=params)
    response = requested.json()
    
    try:
        hotel_df.append(response['results'][0]['name'])
    except:
        hotel_df.append("")

In [63]:
best_weather_df["Hotel Name"] = hotel_df
best_weather_df
best_weather_df = best_weather_df.dropna(how='any')
best_weather_df

C:\Users\ICPC\anaconda3\envs\Pythondata\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Windspeed,Hotel Name
0,hermanus,83.0,7200.0,1.620053e+09,38.0,-34.4187,19.2345,80.01,2.01,Hermanus
1,tomatlan,2.0,-18000.0,1.620053e+09,31.0,19.9333,-105.2500,79.61,0.40,TomatlÃ¡n
2,cabo san lucas,1.0,-21600.0,1.620053e+09,17.0,22.8909,-109.9124,77.00,6.91,Cabo San Lucas
3,lata,34.0,3600.0,1.620053e+09,40.0,40.1629,-8.3327,75.00,9.84,Coimbra
4,bardiyah,100.0,7200.0,1.620053e+09,24.0,31.7561,25.0865,88.99,6.93,Bardiyah
5,gat,31.0,10800.0,1.620053e+09,29.0,31.6100,34.7642,84.00,9.40,Kiryat Gat
6,ongandjera,9.0,7200.0,1.620053e+09,32.0,-17.8833,15.0667,83.82,9.26,Okahao
7,edelira,0.0,-14400.0,1.620053e+09,36.0,-26.7500,-55.2667,85.01,8.63,Edelira
8,chechat,62.0,19800.0,1.620053e+09,22.0,24.7667,75.8833,89.76,6.46,Chechat
9,disa,70.0,19800.0,1.620053e+09,20.0,24.2500,72.1667,89.71,7.56,Deesa
10,seoni,60.0,19800.0,1.620053e+09,35.0,22.0833,79.5333,81.99,3.67,Seoni
11,buritizeiro,0.0,-10800.0,1.620053e+09,39.0,-17.3511,-44.9622,83.26,4.85,Pirapora
12,cassilandia,0.0,-14400.0,1.620053e+09,27.0,-19.1133,-51.7342,87.60,7.31,CassilÃ¢ndia
13,vathi,0.0,10800.0,1.620053e+09,30.0,38.4000,23.6000,86.00,3.44,Vathy
14,khoni,0.0,14400.0,1.620053e+09,27.0,42.3226,42.4206,87.80,3.44,Khoni
15,springbok,99.0,7200.0,1.620053e+09,21.0,-29.6643,17.8865,76.05,4.03,Springbok
16,gazanjyk,100.0,18000.0,1.620053e+09,18.0,39.2446,55.5154,77.38,6.17,Bereket
17,kruisfontein,2.0,7200.0,1.620053e+09,36.0,-34.0033,24.7314,76.69,2.64,Humansdorp
18,najran,75.0,10800.0,1.620053e+09,14.0,17.4924,44.1277,91.40,6.91,Najran
19,kondagaon,49.0,19800.0,1.620053e+09,35.0,19.6000,81.6667,82.63,3.83,Kondagaon
20,sesheke,10.0,7200.0,1.620053e+09,32.0,-17.4759,24.2968,79.38,6.35,Sesheke
21,vredendal,100.0,7200.0,1.620054e+09,28.0,-31.6683,18.5012,77.72,9.33,Vredendal

In [64]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

AttributeError: 'list' object has no attribute 'iterrows'

In [ ]:
# Add marker layer ontop of heat map


# Display figure